version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Astaroth1507
      MYSQL_DATABASE: database_app
      MYSQL_USER: Alex
      MYSQL_PASSWORD: Astaroth1507
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
  api:
    image: apicrud
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - mynetwork
  frontend:
    image: frontendcrud
    ports:
      - "3000:80"
    networks:
      - mynetwork
volumes:
  mysql-data:

networks:
  mynetwork:
